apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: todo
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      secretKeyRef:
        name: redpanda-secrets
        key: REDPANDA_BROKERS
    - name: consumerGroup
      value: "todo-service"
    - name: authRequired
      value: "true"
    - name: authUsername
      secretKeyRef:
        name: redpanda-secrets
        key: REDPANDA_USERNAME
    - name: authPassword
      secretKeyRef:
        name: redpanda-secrets
        key: REDPANDA_PASSWORD
    - name: saslMechanism
      value: "SCRAM-SHA-256"
    - name: tlsEnabled
      value: "true"
    - name: maxMessageBytes
      value: "1048576"
auth:
  secretStore: kubernetes
