apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.env.config.DEBUG | quote }}
  LOG_LEVEL: {{ .Values.env.config.LOG_LEVEL | quote }}
  BETTER_AUTH_URL: {{ .Values.env.config.BETTER_AUTH_URL | quote }}
